version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: assignment_review_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - assignment_review_pgdata:/var/lib/postgresql/data

volumes:
  assignment_review_pgdata:
